### ISSUE TITLE
Формат файла txt

### ISSUE THREAD

**Issue by LvovMax** [geokar2006/ModsIssues#11]
Здравствуйте! Мне очень нравится ваше творчество, но я не могу лично его оценить. Я ,возможно не первый кто вам это пишет, но что делать после того, когда скачал мод меню на "Poppy playtime" в формате txt , а он весит несколько байтов!? Заранее огромное спасибо!

**Comment by geokar2006** [comment]
В файле ссылка на мод. Первая глава весит пол гигабайта вторая гигабайт, я просто не могу загрузить их напрямую на облако. Открой файл и скачатй.
