### ISSUE TITLE
"Обман" Super Bear Adventure 

### ISSUE THREAD

**Issue by Marti079** [geokar2006/ModsIssues#28]
Я захожу в игру, включаю ноуклип и бессмертие потом лечу в черепаший город, и пытаюсь получить золотого мишку, потом я открываю мишку и мне пишет по всем углам "Обман" и мне не дают мишку. Что делать? Я в настройках ничего не трогал.

**Comment by geokar2006** [comment]
Это защита от читерстава, всех медведей нужно получать честно.
