### ISSUE TITLE
Does not work site for hello neighbor b6 disk does not work

### ISSUE THREAD

**Issue by B6HNnotworksitediskgooglenerabotaet** [geokar2006/ModsIssues#3]
Disk for hello neighbor does not work I click and it does not work and the cache does not give
Re-upload video with link to media fire
My Vk @katya_yamova
Please Write to me

**Comment by geokar2006** [comment]
У меня нет ВК и здесь можно писать на русском. Сайт прекрасно работает, я проверил только что. С гугл диска всё прекрасно скачивается.
