### ISSUE TITLE
Ничего/ nothing

### ISSUE THREAD

**Issue by VladiSlav0023** [geokar2006/ModsIssues#46]

**Comment by geokar2006** [comment]
Как я понимаю для шифровки использован какой-то алгоритм (xor, цезарь, aes и т.п.), а после результат зашифрован обычным base64. 
На просто расшифровку без нечего могут уйти века. 

Т.к. код расшифровки и ключ есть в lib, то можно легко всё расшифровать, но придётся полазить по коду и найти место, где файлы открываются и расшифровываются. Тебе нужно научиться пользоваться ida и, изучая код игры через неё, написать алгоритм расшифровки.

**Comment by VladiSlav0023** [comment]
через папку lib  можно расшифровать не используя ключ

**Comment by VladiSlav0023** [comment]
и не факт что все есть в папке lib (код и ключ)

**Comment by geokar2006** [comment]
Это не папка, это набор библиотек, и сами по себе они ничего расшифровывать не будут. Нужно либо их анализировать и восстанавливать код, либо также анализировать, но написать код, который используя данные библиотеки будет расшифровывать файлы.

**Comment by VladiSlav0023** [comment]
Есть правда небольшое осложнение там 16 файлов so. Получается надо все файлы посмотреть ? https://drive.google.com/file/d/1Cdlbw7aJZ_v9MnZ7JSDyHHb-PPLkFrSk/view?usp=sharing

**Comment by geokar2006** [comment]
Нет, нужно знать движок игры и его особенности, чтобы без проблем определить библиотеку.

**Comment by VladiSlav0023** [comment]
Движок Unity

**Comment by geokar2006** [comment]
На данный момент почти все игры сделанные на этом движке используют одну технологию: il2cpp. Почитай информацию про неё и возможно поймёшь.
